/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import java.text.SimpleDateFormat;  
import java.util.Date; 
import java.text.ParseException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
/**
 *
 * @author Rikard Söderek
 */
public class HittaAlienInfo extends javax.swing.JFrame {
    
    private InfDB idb;
    public static String userID;

    /**
     * Creates new form HittaAlienInfo
     */
    public HittaAlienInfo(String userID) {
        initComponents();
        
        this.userID = userID;
        
    try{
            idb = new InfDB("mibdb", "3306", "mibdba","mibkey");
           System.out.println("Allt fungerar (hittills))");
        }
        
        catch(InfException ex){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avbryt = new javax.swing.JButton();
        franDatumSpinner = new javax.swing.JSpinner();
        franLabel = new javax.swing.JLabel();
        sokRasBox = new javax.swing.JComboBox<>();
        rasLabel = new javax.swing.JLabel();
        tillLabel = new javax.swing.JLabel();
        tillDatumSpinner = new javax.swing.JSpinner();
        sokRasLabel = new javax.swing.JLabel();
        AlienIDLabel = new javax.swing.JLabel();
        sokAllInfoLabel = new javax.swing.JLabel();
        VisaAliensefterDatumButton = new javax.swing.JButton();
        VisaAliensEfterRasButton = new javax.swing.JButton();
        sokDatumLabel = new javax.swing.JLabel();
        resultatTextArea = new javax.swing.JTextArea();
        jAlienID = new javax.swing.JTextField();
        jScrollPaneInfo = new javax.swing.JScrollPane();
        alienTable = new javax.swing.JTable();
        visaInfo = new javax.swing.JButton();
        InfoBesökare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Avbryt.setText("Avbryt");
        Avbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvbrytActionPerformed(evt);
            }
        });

        franDatumSpinner.setModel(new javax.swing.SpinnerDateModel());

        franLabel.setText("Från:");

        sokRasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boglodite", "Squid", "Worm" }));

        rasLabel.setText("Ras:");
        rasLabel.setPreferredSize(null);

        tillLabel.setText("Till:");

        tillDatumSpinner.setModel(new javax.swing.SpinnerDateModel());

        sokRasLabel.setText("Lista aliens av en viss ras");

        AlienIDLabel.setText("Ange ID:");

        sokAllInfoLabel.setText("Sök all information om enskild alien");

        VisaAliensefterDatumButton.setText("Visa");
        VisaAliensefterDatumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaAliensefterDatumButtonActionPerformed(evt);
            }
        });

        VisaAliensEfterRasButton.setText("Visa");
        VisaAliensEfterRasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaAliensEfterRasButtonActionPerformed(evt);
            }
        });

        sokDatumLabel.setText("Lista aliens registrerade mellan datum");

        resultatTextArea.setEditable(false);
        resultatTextArea.setBackground(new java.awt.Color(255, 255, 255));
        resultatTextArea.setColumns(20);
        resultatTextArea.setRows(5);

        jAlienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlienIDActionPerformed(evt);
            }
        });

        alienTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        alienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Alien_ID", "Registreringsdatum", "Epost", "Lösenord", "Namn", "Telefon", "Plats", "Ansvarig_Agent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alienTable.setRowHeight(40);
        jScrollPaneInfo.setViewportView(alienTable);

        visaInfo.setText("Visa info");
        visaInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaInfoActionPerformed(evt);
            }
        });

        InfoBesökare.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InfoBesökare.setText("Hitta information om specifika Besökare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Avbryt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(AlienIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(visaInfo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneInfo)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(VisaAliensefterDatumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sokRasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(VisaAliensEfterRasButton))
                                    .addComponent(sokRasLabel)
                                    .addComponent(sokDatumLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tillLabel)
                                            .addComponent(franLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(franDatumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tillDatumSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(resultatTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoBesökare)
                            .addComponent(sokAllInfoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoBesökare)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sokRasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sokRasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VisaAliensEfterRasButton))
                        .addGap(35, 35, 35)
                        .addComponent(sokDatumLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(franDatumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(franLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tillDatumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tillLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(VisaAliensefterDatumButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(resultatTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(sokAllInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlienIDLabel)
                    .addComponent(jAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visaInfo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Avbryt)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvbrytActionPerformed
    //Avbryt
      dispose();
    }//GEN-LAST:event_AvbrytActionPerformed

    private String sökAllInfo(int iD){
        //Metod för att söka upp all Alien-info
        
        //Sträng-variablar för att lagra inforation om dessa
        String resultatsträng = "";
        String ras = "";
        String extra = "";
        
        try{
        
            // Ser om Alien_ID tillhör en Boglodite och stämmer det hämtas information
        if (idb.fetchSingle("SELECT ALIEN_ID FROM BOGLODITE WHERE ALIEN_ID = " + iD) != null){
                        ras = "Boglodite";
                        extra = "Antal boogies:\n  " + idb.fetchSingle("SELECT ANTAL_BOOGIES FROM BOGLODITE WHERE ALIEN_ID = " + iD);
                    }
                    // Ser om Alien_ID tillhör en Squid och stämmer det hämtas information
                    else if(idb.fetchSingle("SELECT ALIEN_ID FROM SQUID WHERE ALIEN_ID = " + iD) != null){
                        ras = "Squid";
                        extra = "Antal armar:\n  " + idb.fetchSingle("SELECT ANTAL_ARMAR FROM SQUID WHERE ALIEN_ID = " + iD);                        
                    }
                    // Ser om Alien_ID tillhör en Worm och stämmer det hämtas information
                    else if(idb.fetchSingle("SELECT ALIEN_ID FROM WORM WHERE ALIEN_ID = " + iD) != null){
                        ras = "Worm";
                    }    
        
        // Rad hämtas från Alien-tabellen i databasen och är baserat på det Alien_ID:et som skrivs in
        HashMap<String, String> aliens = idb.fetchRow("SELECT * FROM ALIEN WHERE ALIEN_ID = " + iD);
        
        // Information sammanställs från den rad som hämtas och skapar en resultatsträng
        resultatsträng = "Namn:\n  " + aliens.get("NAMN")
            + "\nAlienID:\n  " + aliens.get("ALIEN_ID")
            + "\nRegistreringsdatum:\n  " + aliens.get("REGISTRERINGSDATUM")
            + "\nTelefon:\n  " + aliens.get("TELEFON")
            + "\n----------"
            + "\nRas:\n  " + ras
            + "\n" + extra    
            + "\n----------"
            + "\nOmråde:\n  " + idb.fetchSingle("SELECT BENAMNING FROM OMRADE WHERE OMRADES_ID = (SELECT FINNS_I FROM PLATS WHERE PLATS_ID = " + Integer.parseInt(aliens.get("PLATS")) + ")")
            + "\nPlats:\n  " + idb.fetchSingle("SELECT BENAMNING FROM PLATS WHERE PLATS_ID = " + Integer.parseInt(aliens.get("PLATS")))
            + "\n----------"
                
            + "\nAnsvarig Agent:\n  " + idb.fetchSingle("SELECT NAMN FROM AGENT WHERE AGENT_ID = " + Integer.parseInt(aliens.get("ANSVARIG_AGENT")));
        }
        catch (InfException undantag){
            JOptionPane.showMessageDialog(null, "Något gick fel med databasuppkopplingen!");
            System.out.println("Något gick fel! " + undantag);
        }
        return resultatsträng;
    }    
    
    private void VisaAliensefterDatumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaAliensefterDatumButtonActionPerformed
        //Visa Aliens-knapp efter datum
        
        try{
            // Det som händer är att en SimpleDateFormat konverterar och formaterar datum till strängar med formatet "yyyy-MM-dd".
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            // frånDatumSpinner och tillDatumSpinner konverteras och formateras till strängar med det datumformatet som angivs
            String franD = dateFormat.format(franDatumSpinner.getValue());
            String tillD = dateFormat.format(tillDatumSpinner.getValue());

            //Lagra resultatet från databas-frågan
            String resultatsträng = "";
            // En lista av alien-namn hämtas från Alien-tabellen där registreringsdatumet ligger inom det datuminvervall som angivs
            ArrayList<String> alienMellanDatum = idb.fetchColumn("SELECT NAMN FROM ALIEN WHERE REGISTRERINGSDATUM BETWEEN \'" + franD + "\' AND \'" + tillD + "\'");
            
            // Varje alien i listan loopas igenom vilket skapar resultatsträngen
            for (String alien : alienMellanDatum){
                resultatsträng += alien + "\n";
            }
            resultatTextArea.setText(resultatsträng);
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
    }//GEN-LAST:event_VisaAliensefterDatumButtonActionPerformed

    private void VisaAliensEfterRasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaAliensEfterRasButtonActionPerformed
        // Visa-knapp för aliens efter ras
        
        // Namn hämtas och visas på aliens baserat på rasen som väljs i sökRasBox
        try{
            String sökRas = sokRasBox.getSelectedItem().toString().toUpperCase();
            String resultatsträng = "";
            ArrayList<String> rasAliens = idb.fetchColumn("SELECT NAMN FROM ALIEN WHERE ALIEN_ID IN (SELECT ALIEN_ID FROM " + sökRas + ")");
            
            // Varje alien i listan loopas igenom vilket skapar resultatsträngen
            for (String rasAlien : rasAliens){
                resultatsträng += rasAlien + "\n";
            }
            resultatTextArea.setText(resultatsträng);
        }
        catch(InfException undantag){
            System.out.println("Något gick fel! " + undantag);
        }
    }//GEN-LAST:event_VisaAliensEfterRasButtonActionPerformed

    private void jAlienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlienIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlienIDActionPerformed

    private void visaInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaInfoActionPerformed
        HashMap<String, String> alien; // Information om agenten lagras i en HashMap

        try {
            // Alien ID hämtas från ett textfältet jAlienID
            String alienID = jAlienID.getText(); //

            String fraga = "SELECT * FROM alien WHERE Alien_ID ='" + alienID + "'";
            alien = idb.fetchRow(fraga); // Variabeln agent = Visar en rad med information om agenten

            // Agentens information presenteras i tabellen
            alienTable.setValueAt(alien.get("Alien_ID"), 0, 0);               // Kolumn 1
            alienTable.setValueAt(alien.get("Namn"), 0, 4);                   // Kolumn 2
            alienTable.setValueAt(alien.get("Epost"), 0, 2);                  // Kolumn 3
            alienTable.setValueAt(alien.get("Losenord"), 0, 3);               // Kolumn 4
            alienTable.setValueAt(alien.get("Telefon"), 0, 5);                // Kolumn 5
            alienTable.setValueAt(alien.get("Plats"), 0, 6);                 // Kolumn 6
            alienTable.setValueAt(alien.get("Registreringsdatum"), 0, 1);          // Kolumn 7
            alienTable.setValueAt(alien.get("Ansvarig_Agent"), 0, 7);      // Kolumn 8

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kunde inte hitta Alien");
        }

    }//GEN-LAST:event_visaInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HittaAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HittaAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HittaAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HittaAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HittaAlienInfo(userID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlienIDLabel;
    private javax.swing.JButton Avbryt;
    private javax.swing.JLabel InfoBesökare;
    private javax.swing.JButton VisaAliensEfterRasButton;
    private javax.swing.JButton VisaAliensefterDatumButton;
    private javax.swing.JTable alienTable;
    private javax.swing.JSpinner franDatumSpinner;
    private javax.swing.JLabel franLabel;
    private javax.swing.JTextField jAlienID;
    private javax.swing.JScrollPane jScrollPaneInfo;
    private javax.swing.JLabel rasLabel;
    private javax.swing.JTextArea resultatTextArea;
    private javax.swing.JLabel sokAllInfoLabel;
    private javax.swing.JLabel sokDatumLabel;
    private javax.swing.JComboBox<String> sokRasBox;
    private javax.swing.JLabel sokRasLabel;
    private javax.swing.JSpinner tillDatumSpinner;
    private javax.swing.JLabel tillLabel;
    private javax.swing.JButton visaInfo;
    // End of variables declaration//GEN-END:variables
}
