
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */

public class RegistreringAndringavAgent extends javax.swing.JFrame {
    
    private InfDB idb;
    Connection con;
        





//try {
//            con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
//        } catch (SQLException ex) {
//            Logger.getLogger(RegistreringAndringavAgent.class.getName()).log(Level.SEVERE, null, ex);
//        }

    
    /**
     * Creates new form NyregistreringAvAgent
     */
    public RegistreringAndringavAgent() {
        initComponents();
//        initDBConnection();
        
        try{
            idb = new InfDB("mibdb", "3306", "mibdba","mibkey");
            con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
            System.out.println("Allt fungerar (hittills))");
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LaggTill = new javax.swing.JButton();
        TaBortAgent = new javax.swing.JButton();
        SparaAndringar = new javax.swing.JButton();
        RegistreraAndraAgent = new javax.swing.JLabel();
        NamnLabel = new javax.swing.JLabel();
        TelefonTextfield = new javax.swing.JTextField();
        AgentIDLabel = new javax.swing.JLabel();
        NamnTextfield = new javax.swing.JTextField();
        TelefonLabel = new javax.swing.JLabel();
        AnstDatumLabel = new javax.swing.JLabel();
        AdminLabel = new javax.swing.JLabel();
        EpostLabel = new javax.swing.JLabel();
        LosenordLabel = new javax.swing.JLabel();
        AnstDatumTextfield = new javax.swing.JTextField();
        AgentIdTextfield = new javax.swing.JTextField();
        AdminTextfield = new javax.swing.JTextField();
        EpostTextfield = new javax.swing.JTextField();
        LosenordTextfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        VisaAgent = new javax.swing.JButton();
        OmradeTextfield = new javax.swing.JTextField();
        OmradeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Rensa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LaggTill.setText("Lägg till");
        LaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaggTillActionPerformed(evt);
            }
        });

        TaBortAgent.setText("Ta bort");
        TaBortAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaBortAgentActionPerformed(evt);
            }
        });

        SparaAndringar.setText("Uppdatera");
        SparaAndringar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SparaAndringarActionPerformed(evt);
            }
        });

        RegistreraAndraAgent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegistreraAndraAgent.setText("Registrering, ändring och borttagelse av Agent");

        NamnLabel.setText("Namn:");

        AgentIDLabel.setText("Agent ID:");

        TelefonLabel.setText("Telefon:");

        AnstDatumLabel.setText("Anställningsdatum:");

        AdminLabel.setText("Admin:");

        EpostLabel.setText("E-post:");

        LosenordLabel.setText("Lösenord:");

        AgentIdTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentIdTextfieldActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Namn", "Telefon", "AnstDatum", "Admin", "E-post", "Lösenord", "Område"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jButton4.setText("Avbryt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        VisaAgent.setText("Visa agenter");
        VisaAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaAgentActionPerformed(evt);
            }
        });

        OmradeTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OmradeTextfieldActionPerformed(evt);
            }
        });

        OmradeLabel.setText("Område:");

        jLabel1.setText("För att Lägga till, Uppdatera & Ta bort - tryck nedan");

        Rensa.setText("Rensa");
        Rensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamnLabel)
                                    .addComponent(AgentIDLabel)
                                    .addComponent(TelefonLabel)
                                    .addComponent(EpostLabel)
                                    .addComponent(LosenordLabel)
                                    .addComponent(OmradeLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AdminLabel)
                                    .addGap(15, 15, 15)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(LaggTill)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AnstDatumLabel)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LosenordTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(EpostTextfield)
                    .addComponent(AdminTextfield)
                    .addComponent(TelefonTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(AnstDatumTextfield)
                    .addComponent(AgentIdTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(NamnTextfield)
                    .addComponent(OmradeTextfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegistreraAndraAgent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(SparaAndringar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Rensa)
                        .addGap(54, 54, 54)
                        .addComponent(TaBortAgent)
                        .addGap(199, 199, 199)
                        .addComponent(VisaAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(RegistreraAndraAgent)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgentIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgentIdTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NamnTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamnLabel))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefonLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnstDatumTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnstDatumLabel))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EpostTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EpostLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LosenordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LosenordLabel))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OmradeLabel)
                            .addComponent(OmradeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LaggTill)
                            .addComponent(SparaAndringar)
                            .addComponent(Rensa)
                            .addComponent(TaBortAgent))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VisaAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaggTillActionPerformed
        //Lägg till Agent
        
        if(AgentIdTextfield.getText().equals("")||NamnTextfield.getText().equals("")|| TelefonTextfield.getText().equals("")||AnstDatumTextfield.getText().equals("")||AdminTextfield.getText().equals("")||EpostTextfield.getText().equals("")||LosenordTextfield.getText().equals("")||OmradeTextfield.getText().equals("")){
            
           //Om någon av fälten lämnas tomma
           JOptionPane.showMessageDialog(this, "Var god fyll i all data!");
        }else{
           //Om all data fylls i
           // Samlar data i String Arrays
           String data[] = {AgentIdTextfield.getText(), NamnTextfield.getText(), TelefonTextfield.getText(), AnstDatumTextfield.getText(), AdminTextfield.getText(), EpostTextfield.getText(), LosenordTextfield.getText(), OmradeTextfield.getText()}; 
        
        
        DefaultTableModel tblModel = (DefaultTableModel) Table.getModel();
        //Adderar String array data
        tblModel.addRow(data); //rad adderad
        
        //Lyckat-meddelande
        JOptionPane.showMessageDialog(this, "Data tillagd!");
        //Rensar textfält för ny uppgift
        AgentIdTextfield.setText("");
        NamnTextfield.setText("");
        TelefonTextfield.setText("");
        AnstDatumTextfield.setText("");
        AdminTextfield.setText("");
        EpostTextfield.setText("");
        LosenordTextfield.setText("");
        OmradeTextfield.setText("");
       
      }
        
    }//GEN-LAST:event_LaggTillActionPerformed

    private void SparaAndringarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SparaAndringarActionPerformed
        //Uppdatera AgentInfo
       
        if(AgentIdTextfield.getText().equals("")||NamnTextfield.getText().equals("")|| TelefonTextfield.getText().equals("")||AnstDatumTextfield.getText().equals("")||AdminTextfield.getText().equals("")||EpostTextfield.getText().equals("")||LosenordTextfield.getText().equals("")||OmradeTextfield.getText().equals(""))
            
           //Om någon av fälten lämnas tomma
           {JOptionPane.showMessageDialog(this, "Var god välj rad från tabellen!");}
        
        else{DefaultTableModel tblModel = (DefaultTableModel) Table.getModel();
        
       String AgentID = AgentIdTextfield.getText();
       String Namn = NamnTextfield.getText();
       String Telefon = TelefonTextfield.getText();
       String Anstallningsdatum = AnstDatumTextfield.getText();
       String Admin = AdminTextfield.getText();
       String Epost = EpostTextfield.getText();
       String Losenord = LosenordTextfield.getText();
       String Omrade = OmradeTextfield.getText();
       
       tblModel.setValueAt(AgentID, Table.getSelectedRow(), 0);
       tblModel.setValueAt(Namn, Table.getSelectedRow(), 1);
       tblModel.setValueAt(Telefon, Table.getSelectedRow(), 2);
       tblModel.setValueAt(Anstallningsdatum, Table.getSelectedRow(), 3);
       tblModel.setValueAt(Admin, Table.getSelectedRow(), 4);
       tblModel.setValueAt(Epost, Table.getSelectedRow(), 5);
       tblModel.setValueAt(Losenord, Table.getSelectedRow(), 6);
       tblModel.setValueAt(Omrade, Table.getSelectedRow(), 7);
       
       JOptionPane.showMessageDialog(this, "Uppdatering lyckades!");
        }
        
    }//GEN-LAST:event_SparaAndringarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Avbryt
                  JFrame frame = new JFrame("Avbryt");
        if(JOptionPane.showConfirmDialog(frame, "Är du säker på att du vill avbryta?", "Avbryt",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION);
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TaBortAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaBortAgentActionPerformed
        //Ta bort agent
        //Hämta tabell
        
        DefaultTableModel tblModel = (DefaultTableModel) Table.getModel();
        
        //Frågar om rad ska tas bort
        //Tar bort rad
        
         JFrame frame = new JFrame("Ta bort");
        if(JOptionPane.showConfirmDialog(frame, "Är du säker på att du vill ta bort agenten?", "Ta bort",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION);
           
        if(Table.getSelectedRowCount()==1){
            //Om en rad är vald, så radera
            tblModel.removeRow(Table.getSelectedRow());
                        
        }else{
            if(Table.getRowCount()==0){
                //Om tabellen är tom och saknar data så visas ett meddelande
                JOptionPane.showMessageDialog(this, "Tabellen är tom");
            }else{
                //Om tabellen inte är tom men rad är inte vald eller flera rader är valda
                JOptionPane.showMessageDialog(this, "Var god välj En rad");
            }
        }
        
    }//GEN-LAST:event_TaBortAgentActionPerformed

    private void AgentIdTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentIdTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgentIdTextfieldActionPerformed

    private void VisaAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaAgentActionPerformed
<<<<<<< HEAD
        try {
            // Ska visa alla registerade agenter

            con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
        } catch (SQLException ex) {
            Logger.getLogger(RegistreringAndringavAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
=======
        //Knapp för att visa alla registerade agenter
>>>>>>> d656df77fd7594e446ab6120e83a25b0cc0d680e
        
        String sql ="SELECT * FROM Agent";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)Table.getModel();
            model.setRowCount(0);
            while(rs.next()){
            model.addRow(new String[] { rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8) });            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_VisaAgentActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Visar data i textfälten
        
        DefaultTableModel tblModel = (DefaultTableModel) Table.getModel();
        
        // Visar data i valt textfält
        
        String tblAgent_ID = tblModel.getValueAt(Table.getSelectedRow(),0).toString();
        String tblNamn = tblModel.getValueAt(Table.getSelectedRow(),1).toString();
        String tblTelefon = tblModel.getValueAt(Table.getSelectedRow(),2).toString();
        String tblAnstallningsdatum = tblModel.getValueAt(Table.getSelectedRow(),3).toString();
        String tblAdministrator = tblModel.getValueAt(Table.getSelectedRow(),4).toString();
        String tblEpost = tblModel.getValueAt(Table.getSelectedRow(),5).toString();
        String tblLosenord = tblModel.getValueAt(Table.getSelectedRow(),6).toString();
        String tblOmrade = tblModel.getValueAt(Table.getSelectedRow(),7).toString();
        
        // Välj till textfält
        
        AgentIdTextfield.setText(tblAgent_ID);
        NamnTextfield.setText(tblNamn);
        TelefonTextfield.setText(tblTelefon);
        AnstDatumTextfield.setText(tblAnstallningsdatum);
        AdminTextfield.setText(tblAdministrator);
        EpostTextfield.setText(tblEpost);
        LosenordTextfield.setText(tblLosenord);
        OmradeTextfield.setText(tblOmrade);
        
    }//GEN-LAST:event_TableMouseClicked

    private void OmradeTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OmradeTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OmradeTextfieldActionPerformed

    private void RensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RensaActionPerformed
        // Rensar allt i textfälten
        
        AgentIdTextfield.setText(null);
        NamnTextfield.setText(null);
        TelefonTextfield.setText(null);
        AnstDatumTextfield.setText(null);
        AdminTextfield.setText(null);
        EpostTextfield.setText(null);
        LosenordTextfield.setText(null);
        OmradeTextfield.setText(null);
        
    }//GEN-LAST:event_RensaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreringAndringavAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreringAndringavAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreringAndringavAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreringAndringavAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreringAndringavAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JTextField AdminTextfield;
    private javax.swing.JLabel AgentIDLabel;
    private javax.swing.JTextField AgentIdTextfield;
    private javax.swing.JLabel AnstDatumLabel;
    private javax.swing.JTextField AnstDatumTextfield;
    private javax.swing.JLabel EpostLabel;
    private javax.swing.JTextField EpostTextfield;
    private javax.swing.JButton LaggTill;
    private javax.swing.JLabel LosenordLabel;
    private javax.swing.JTextField LosenordTextfield;
    private javax.swing.JLabel NamnLabel;
    private javax.swing.JTextField NamnTextfield;
    private javax.swing.JLabel OmradeLabel;
    private javax.swing.JTextField OmradeTextfield;
    private javax.swing.JLabel RegistreraAndraAgent;
    private javax.swing.JButton Rensa;
    private javax.swing.JButton SparaAndringar;
    private javax.swing.JButton TaBortAgent;
    private javax.swing.JTable Table;
    private javax.swing.JLabel TelefonLabel;
    private javax.swing.JTextField TelefonTextfield;
    private javax.swing.JButton VisaAgent;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
